source 'https://rubygems.org'

gem 'bundler', '>= 1.14.6'
gem 'json', '~> 1.8.3'
gem 'colorize'
gem 'activesupport', '~> 5.0.2'
gem 'celluloid', '~> 0.17.3', require: 'celluloid/current'
gem 'awesome_print'
gem 'mechanize'
gem 'dotenv', require: 'dotenv/load'
gem 'public_suffix', '>= 3.0.1'
gem 'crass'
gem 'open_uri_redirections'
gem 'addressable'